name: "Continuous Integration"
on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'

      - name: Checkout branch
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_call'
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
